# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  node_version: 14

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Setup clojure
      - uses: DeLaGuardo/setup-clojure@master
        with:
          # To use Clojure CLI 1.10.1.561 based on tools.deps
          cli: '1.10.1.469'

      # Build the project
      - name: Build shadow
        uses: borales/actions-yarn@v2.0.0
      - run: |
          cd $GITHUB_WORKSPACE/backend
          echo $(pwd)
          yarn
          yarn shadow-cljs release backend
          cd $GITHUB_WORKSPACE/backend/build
          zip deployment.zip main.js
      # Deploy to lambda
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGIOn }}
          function_name: din-page-titles
          zip_file: backend/build/deployment.zip
          memory_size: 128
          timeout: 10
          handler: handler
          role: arn:aws:iam::963585794345:role/service-role/din-page-titles-role-sdscagg4
          runtime: nodejs14.x
